### ISSUE TITLE
Python builtin ctypes module depends on libffi

### ISSUE THREAD

**Issue by funny-falcon** [mingw-w64/mingw-w64#15]
Without installing libffi importing ctypes fails with obscure message starting with:
```
ImportError: DLL load failed while importing _ctypes:  .
```
(at least in UCRT environment)
I've got to google to recognize it requires libffi.

Without fixing it `pip` and many other packages could not work since they indirectly import ctypes.

Looks like python package have to depend on libffi explicitely.

**Comment by Biswa96** [comment]
Are you using mingw packages from msys2?

**Comment by funny-falcon** [comment]
Yes, I'm using msys2 and its packages.

I don't remember if this error happens in msys's mingw64 environment. But it certainly happens in msys's ucrt64 environment.

**Comment by Biswa96** [comment]
Please report the issues here https://github.com/msys2/MINGW-packages/issues. Also fill out all the field in that issue form. It'll help to understand the situation.
