### ISSUE TITLE
Not self-containing header "eh.h"

### ISSUE THREAD

**Issue by bernd5** [mingw-w64/mingw-w64#18]
The header file [`eh.h`](https://github.com/mingw-w64/mingw-w64/blob/master/mingw-w64-headers/crt/eh.h) makes use of `std::type_info` without forward declaration or including `<typeinfo>`.
Could this be fixed?

**Comment by Biswa96** [comment]
Thanks for reporting the issue. I have sent a patch to fix the issue in upstream mailing list, here https://sourceforge.net/p/mingw-w64/mailman/message/37747605/
