### ISSUE TITLE
website has its HTTPS certificate expired

### ISSUE THREAD

**Issue by vszakats** [mingw-w64/mingw-w64#2]
https://mingw-w64.org/ has its HTTPS certificate expired a while ago.
Could it be renewed and/or replaced with a free Let's Encrypt cert?:

![Screen Shot 2020-03-27 at 16 20 09](https://user-images.githubusercontent.com/1446897/77771605-2ee57500-7047-11ea-817a-88e5395b5540.png)

**Comment by lhmouse** [comment]
It looks like nobody is taking care of it at the moment.

**Comment by vszakats** [comment]
Thanks, I'll be reverting to use <https://sourceforge.net/projects/mingw-w64/> instead of the above.
