### ISSUE TITLE
can not read utf-8 charter from stdin

### ISSUE THREAD

**Issue by pangguoming** [mingw-w64/mingw-w64#20]
i am doing a C language project with MINGW64 \ GCC 10.2.0 on windows.
when i read a UTF-8 or gbk string from stdin ( fgets(buf, QUERYBUF_LEN, stdin) ), it just read the top byte of UTF-8 or gbk charter

**Comment by pangguoming** [comment]
the code works well on linux

**Comment by wszqkzqk** [comment]
This may be the bug (or feature🤣🤣🤣) of windows. MSVC cannot, either. Maybe you need to set the codepage by yourself?

**Comment by pangguoming** [comment]
> This may be the bug (or feature🤣🤣🤣) of windows. MSVC cannot, either. Maybe you need to set the codepage by yourself?

yes it is. thanks
