### ISSUE TITLE
The performance of `Math.pow ()` is poor sometimes

### ISSUE THREAD

**Issue by wszqkzqk** [mingw-w64/mingw-w64#21]
When the `exponent` of `Math.pow()` is integer, the performance of mingw-w64 is better than `ucrtbase.dll`. However, when the exponent is a float, mingw-w64 is **much slower**.

Env: mingw-w64 in msys2 UCRT64, `gcc 12.2.0`, `mingw-w64-crt` on the current git version.

Test example (written in vala):
```vala
delegate double CalcFunc (double x, double y);

int64 libc_pow_time_cost (double x, double y, uint cycles) {
    CalcFunc pow;
    void* _pow;
    Module module = Module.open ("ucrtbase.dll", ModuleFlags.LAZY);
    module.symbol ("pow", out _pow);
    pow = (CalcFunc) _pow;
    var start = get_monotonic_time ();
    for (uint i = 0; i < cycles; i += 1) {
        pow (x, y);
    }
    return get_monotonic_time () - start;
}

int64 math_pow_time_cost (double x, double y, uint cycles) {
    var start = get_monotonic_time ();
    for (uint i = 0; i < cycles; i += 1) {
        Math.pow (x, y);
    }
    return get_monotonic_time () - start; 
}

string? input (string? info = null, ...) {
    if (info != null) {
        print ((!) info, va_list ());
    }
    return stdin.read_line ();
}

void main () {
    Intl.setlocale ();
    var x = double.parse (input ("Please enter the base:\n"));
    var y = double.parse (input ("Please enter the exponent:\n"));
    var cycles = uint.parse (input ("Please enter the number of cycles:\n"));
    print ("`pow()' in ucrtbase.dll cost: %lld microseconds\n", libc_pow_time_cost (x, y, cycles));
    print ("`pow()' in mingw-w64 cost: %lld microseconds\n", math_pow_time_cost (x, y, cycles));
}
```

Complie with `valac --pkg gmodule-2.0 -X -O3 -X -march=native test-pow.vala`

Run:
```bash
Please enter the base:
1.23
Please enter the exponent:
7.89
Please enter the number of cycles:
1000000
`pow()' in ucrtbase.dll cost: 17327 microseconds
`pow()' in mingw-w64 cost: 87468 microseconds
```

```bash
Please enter the base:
1.23
Please enter the exponent:
8
Please enter the number of cycles:
1000000
`pow()' in ucrtbase.dll cost: 17328 microseconds
`pow()' in mingw-w64 cost: 11071 microseconds
```

**Comment by wszqkzqk** [comment]
May we refer to this? [`msun` of FreeBSD](https://svnweb.freebsd.org/base/head/lib/msun/src/e_pow.c?view=markup)

**Comment by lhmouse** [comment]
On x86_64, it looks like the `pow()` function is implemented with x87 FPU instead of SSE. Not only is it slower, it's also deprecated.

If you have a better implementation, please send a patch to mingw-w64-public@lists.sourceforge.net.

**Comment by wszqkzqk** [comment]
> On x86_64, it looks like the `pow()` function is implemented with x87 FPU instead of SSE. Not only is it slower, it's also deprecated.
> 
> If you have a better implementation, please send a patch to [mingw-w64-public@lists.sourceforge.net](mailto:mingw-w64-public@lists.sourceforge.net).

Sorry, it's out of my ability. I know little about the rules for developing low-level libraries. 😣😣😣

**Comment by MehdiChinoune** [comment]
Hi @wszqkzqk There were some recent changes to call/use MS functions.
Could you retry again (Of course a full update of your MSYS2 installation).

**Comment by wszqkzqk** [comment]
> ```shell
> 1000000
> ```

Okay. I tried again with latest msys2 environment. Here are the results.

```bash
Please enter the base:
1.23
Please enter the exponent:
7.89
Please enter the number of cycles:
1000000
`pow()' in ucrtbase.dll module costs: 18231 microseconds
`pow()' in msvcrt.dll module costs: 21121 microseconds
Built-in `pow()' in mingw-w64 costs: 17033 microseconds
result: 5.12096
```

```bash
Please enter the base:
1.23
Please enter the exponent:
8
Please enter the number of cycles:
1000000
`pow()' in ucrtbase.dll module costs: 18458 microseconds
`pow()' in msvcrt.dll module costs: 20946 microseconds
Built-in `pow()' in mingw-w64 costs: 17290 microseconds
result: 5.23891
```

It seems that the performance issue was solved.

**Comment by MehdiChinoune** [comment]
Could you close the issue.

**Comment by wszqkzqk** [comment]
Solved upstream.
