### ISSUE TITLE
Function signatures in rpcdce.h are missing const compared to MSDN documentation

### ISSUE THREAD

**Issue by ferkulat** [mingw-w64/mingw-w64#22]
Hello, 
in header mingw64\include\rpcdce.h some functions are missing `const` qualifier for some parameters.
in particular for `UUID *Uuid`.
`RPCRTAPI RPC_STATUS RPC_ENTRY UuidToStringA(UUID *Uuid,RPC_CSTR *StringUuid);`
`RPCRTAPI RPC_STATUS RPC_ENTRY UuidToStringW(UUID *Uuid,RPC_WSTR *StringUuid);`

Please compare to https://learn.microsoft.com/en-us/windows/win32/api/rpcdce/nf-rpcdce-uuidtostring
There might be more, but these I noticed, because I wanted to use them and could not with a `const uuid`.

**Comment by Biswa96** [comment]
> There might be more...

More in which header file?

**Comment by ferkulat** [comment]
> > There might be more...
> 
> More in which header file?

Sorry for confusing you.
I wanted to express, that I did not check any further if there are similar cases in this or other headers.

**Comment by Biswa96** [comment]
It's alright. I wasn't confused, just want to make sure if the issue exists in other headers also.
