### ISSUE TITLE
VirtualAlloc2 and MapViewOfFile3 missing from mingw libs

### ISSUE THREAD

**Issue by dnotq** [mingw-w64/mingw-w64#27]
OS: Win10 pro 22H2
$ gcc --version
gcc.exe (Rev7, Built by MSYS2 project) 13.1.0

I'm trying to use VirtualAlloc2 and MapViewOfFile3, which are available in the mingw `memoryapi.h` but requires `_WIN32_WINNT` and `NTDDI_VERSION` overrides:
```
#define _WIN32_WINNT 0x0A00
#define NTDDI_VERSION 0x0A000005
```

When compiling, the linker cannot find the functions (with or without `-ladvapi32`):

```
$ gcc -o test test.c -lmincore -ladvapi32
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\msys64\tmp\ccfzDMq9.o:test.c:(.text+0x48): undefi
ned reference to `__imp_VirtualAlloc2'
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\msys64\tmp\ccfzDMq9.o:test.c:(.text+0xce): undefi
ned reference to `__imp_MapViewOfFile3'
collect2.exe: error: ld returned 1 exit status
```

The code below will reproduce the error.  If the `*FromApp` versions (i.e. `VirtualAlloc2FromApp` and `MapViewOfFile3FromApp`) for the functions are used, the code compiles and "seems" to work as expected.  It is unclear to me what the actual differences are in these functions from their non `*FromApp` counterparts.

```
// Needed for VirtualAlloc2 and MapViewOfFile3
#define _WIN32_WINNT 0x0A00
#define NTDDI_VERSION 0x0A000005

// gcc -o test test.c -lmincore
// gcc -o test test.c -lmincore -ladvapi32
//
// Search all libs in /e/msys64/mingw64/lib:
// $ for f in lib*.a ; do nm -A $f | grep -i virtualalloc3 ; done
//
// The "FromApp" versions are found and seem to work:
//   VirtualAlloc2FromApp and MapViewOfFile3FromApp
// It is unclear what the actual differences are in these functions from their
// non "FromApp" counterparts.

#include <windows.h>
#include <stdint.h>

int main(void) {

   size_t bufsize = 1024 * 4;

   void *addr = (PCHAR)VirtualAlloc2(NULL, NULL, bufsize, MEM_RESERVE | MEM_RESERVE_PLACEHOLDER, PAGE_NOACCESS, NULL, 0);
   HANDLE map = CreateFileMapping(INVALID_HANDLE_VALUE, NULL, PAGE_READWRITE, 0, (DWORD)bufsize, NULL);
   void *view = MapViewOfFile3(map, NULL, addr, 0, bufsize, MEM_REPLACE_PLACEHOLDER, PAGE_READWRITE, NULL, 0);

   if ( NULL != map )  { CloseHandle(map); }
   if ( NULL != addr ) { VirtualFree(addr, 0, MEM_RELEASE); }
   if ( NULL != view ) { UnmapViewOfFile(view); }

   return 0;
}
```

**Comment by dnotq** [comment]
Thank you!  It is nice to see such a fast response.  I tried to figure it out myself, but quickly realized I have no clue how mingw is set up and I didn't get very far.

**Comment by Biswa96** [comment]
This has been added here https://sourceforge.net/p/mingw-w64/mingw-w64/ci/2fdf3eaa05765caa50f69a91a78f4c916376b09c/

You have to rebuild the crt to get the changes in mincore library. Feel free to close the issue if fixed.

**Comment by dnotq** [comment]
Nice.

I'm not set up to build mingw from sources, I typically follow the releases via pacman.  Let me see what it takes to get a build env going.

**Comment by dnotq** [comment]
These appear to be included now and work as expected.  Thank you!
