### ISSUE TITLE
A typo in `uiautomationcoreapi.h`

### ISSUE THREAD

**Issue by mister-goo** [mingw-w64/mingw-w64#31]
`TreeScope_SubTree` should be `TreeScope_Subtree`.

**Comment by Biswa96** [comment]
Thank you for reporting this issue. The typo also present in uiautomationclient.h file. I have sent the fix to upstream wine project in this merge request https://gitlab.winehq.org/wine/wine/-/merge_requests/3666

The fix will be imported to mingw-w64 after it is merged.

**Comment by jon-y** [comment]
Closing as fixed.
