### ISSUE TITLE
Missing functions in 32-bit `libcabinet.a`

### ISSUE THREAD

**Issue by mister-goo** [mingw-w64/mingw-w64#32]
These [compression API](https://learn.microsoft.com/en-us/windows/win32/cmpapi/compression-api-functions) functions seem to be missing.

**Comment by Biswa96** [comment]
Thank you for reporting the issue. I have sent the patch to fix this in mingw-w64 mailing list https://sourceforge.net/p/mingw-w64/mailman/message/37892664/
