### ISSUE TITLE
undeclared function '__cpuidex'

### ISSUE THREAD

**Issue by Andarwinux** [mingw-w64/mingw-w64#34]
This error occurs when building [zlib-ng](https://github.com/zlib-ng/zlib-ng/blob/develop/arch/x86/x86_features.c#L39) with clang17 and mingw-w64 master.
```
zlib/arch/x86/x86_features.c:39:5: error: call to undeclared function '__cpuidex'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   39 |     __cpuidex((int *)registers, info, subinfo);
      |     ^
1 warning and 1 error generated.
```
https://reviews.llvm.org/D157115
https://github.com/mingw-w64/mingw-w64/commit/2b6c9247613aa830374e3686e09d3b8d582a92a6

**Comment by lazka** [comment]
See 0605217f5d60257a53ec87
