### ISSUE TITLE
ID3D12InfoQueue1 declaration is missing

### ISSUE THREAD

**Issue by n9H07** [mingw-w64/mingw-w64#39]
https://microsoft.github.io/DirectX-Specs/d3d/MessageCallback.html

For the time being, AddVectoredExceptionHandler() for DBG_PRINTEXCEPTION_C and DBG_PRINTEXCEPTION_WIDE_C can be used as an alternative, although it would be preferable if it were implemented.

**Comment by Biswa96** [comment]
I can try to add that symbol and it will take some time to arrive here.

**Comment by Biswa96** [comment]
Journey begins from here https://gitlab.winehq.org/wine/vkd3d/-/merge_requests/495

**Comment by Biswa96** [comment]
ID3D12InfoQueue1 has been added in this commit https://github.com/mingw-w64/mingw-w64/commit/662e1305f86aa797eb7c79c5ae9c63137c79d855
