### ISSUE TITLE
ksmedia.h broken after 01d406ab4

### ISSUE THREAD

**Issue by kasper93** [mingw-w64/mingw-w64#40]
Missing comma in this line:
https://github.com/mingw-w64/mingw-w64/blob/662e1305f86aa797eb7c79c5ae9c63137c79d855/mingw-w64-headers/include/ksmedia.h#L668

Regressed by:
https://github.com/mingw-w64/mingw-w64/commit/01d406ab4d6ccbd1d3b7807ca81d081c88ee204e

CC @robUx4 @lhmouse 

EDIT:

~~Also those new GUIDs should be inside `#ifdef _INC_MMREG` like the rest probably.~~

**Comment by lhmouse** [comment]
在 2023/12/2 10:29, Kacper Michajłow 写道:
> Missing comma in this line:
> https://github.com/mingw-w64/mingw-w64/blob/662e1305f86aa797eb7c79c5ae9c63137c79d855/mingw-w64-headers/include/ksmedia.h#L668 <https://github.com/mingw-w64/mingw-w64/blob/662e1305f86aa797eb7c79c5ae9c63137c79d855/mingw-w64-headers/include/ksmedia.h#L668>
> 
> Regressed by:
> 01d406a <https://github.com/mingw-w64/mingw-w64/commit/01d406ab4d6ccbd1d3b7807ca81d081c88ee204e>


Windows SDK headers (7.1, 8.0, 8.1, 10.0.18362.0, 10.0.19041.0, 10.0.20348.0, 10.0.22000.0, 
10.0.22621.0) only have a few GUIDs in `_INC_MMREG`, from `STATIC_KSDATAFORMAT_SUBTYPE_IEEE_FLOAT` 
to `STATIC_KSDATAFORMAT_SUBTYPE_MPEG`. So probably those new GUIDs should have been defined outside 
that block.




-- 
Best regards,
LIU Hao


From 7f54c78e35c2056a6d972261d70e8ba8fbf1191a Mon Sep 17 00:00:00 2001
From: LIU Hao ***@***.***>
Date: Sat, 2 Dec 2023 14:51:58 +0800
Subject: [PATCH] headers/ksmedia: Tiny fixes to match Windows SDK

Add a missing comma; move `STATIC_KSDATAFORMAT_SUBTYPE_IEC61937_DOLBY_DIGITAL`
and `STATIC_KSDATAFORMAT_SUBTYPE_IEC61937_DTS` outside `#ifdef _INC_MMREG` so
they match Windows SDK 10.0.22621.0.

This closes https://github.com/mingw-w64/mingw-w64/issues/40.

Signed-off-by: LIU Hao ***@***.***>
---
 mingw-w64-headers/include/ksmedia.h | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/mingw-w64-headers/include/ksmedia.h b/mingw-w64-headers/include/ksmedia.h
index 63ac78f82..0cbe3c006 100644
--- a/mingw-w64-headers/include/ksmedia.h
+++ b/mingw-w64-headers/include/ksmedia.h
@@ -652,6 +652,7 @@ DEFINE_GUIDSTRUCT("00000002-0000-0010-8000-00aa00389b71",KSDATAFORMAT_SUBTYPE_AD
 	DEFINE_WAVEFORMATEX_GUID(WAVE_FORMAT_MPEG)
 DEFINE_GUIDSTRUCT("00000050-0000-0010-8000-00aa00389b71",KSDATAFORMAT_SUBTYPE_MPEG);
 #define KSDATAFORMAT_SUBTYPE_MPEG DEFINE_GUIDNAMED(KSDATAFORMAT_SUBTYPE_MPEG)
+#endif /* _INC_MMREG */
 
 #define STATIC_KSDATAFORMAT_SUBTYPE_IEC61937_DOLBY_DIGITAL	\
 	DEFINE_WAVEFORMATEX_GUID(WAVE_FORMAT_DOLBY_AC3_SPDIF)
@@ -662,10 +663,9 @@ DEFINE_GUIDSTRUCT("00000092-0000-0010-8000-00aa00389b71",KSDATAFORMAT_SUBTYPE_IE
 	DEFINE_WAVEFORMATEX_GUID(WAVE_FORMAT_DTS)
 DEFINE_GUIDSTRUCT("00000008-0000-0010-8000-00aa00389b71",KSDATAFORMAT_SUBTYPE_IEC61937_DTS);
 #define KSDATAFORMAT_SUBTYPE_IEC61937_DTS DEFINE_GUIDNAMED(KSDATAFORMAT_SUBTYPE_IEC61937_DTS)
-#endif /* _INC_MMREG */
 
 #define STATIC_KSDATAFORMAT_SUBTYPE_IEC61937_DTS_HD	\
-	0x0000000b,0x0cea,0x0010,0x80,0x00,0x00,0xaa,0x00,0x38,0x9b 0x71
+	0x0000000b,0x0cea,0x0010,0x80,0x00,0x00,0xaa,0x00,0x38,0x9b,0x71
 DEFINE_GUIDSTRUCT("0000000b-0cea-0010-8000-00aa00389b71",KSDATAFORMAT_SUBTYPE_IEC61937_DTS_HD);
 #define KSDATAFORMAT_SUBTYPE_IEC61937_DTS_HD DEFINE_GUIDNAMED(KSDATAFORMAT_SUBTYPE_IEC61937_DTS_HD)
 
-- 
2.42.1

**Comment by kasper93** [comment]
> So probably those new GUIDs should have been defined outside
that block.

Indeed, I haven't looked before, but only those that uses `DEFINE_WAVEFORMATEX_GUID` should be defined in `_INC_MMREG`. So no change necessary here.
