### ISSUE TITLE
internal linkage functions cannt be exported in c++ module

### ISSUE THREAD

**Issue by wre40** [mingw-w64/mingw-w64#41]
Since P2615R1,a function exported in modules shouldnt declare it with internal linkage.
However serval CRT functions such as swprintf decalared with static prefix.
Therefore is it possible to replace static with inline?

**Comment by lhmouse** [comment]
Plain `inline` should be use with care, as it denotes very different things among C89, C99 and C++. At the moment `static inline` is the safest solution, and others would require thorough testing.

**Comment by wre40** [comment]
Thanks
