### ISSUE TITLE
error: 'struct _TEB' has no member named 'ProcessEnvironmentBlock' 

### ISSUE THREAD

**Issue by UserNotfoundR** [mingw-w64/mingw-w64#45]
`precompiled.c: In function 'main':
precompiled.c:85:65: error: 'struct _TEB' has no member named 'ProcessEnvironmentBlock'
   LIST_ENTRY *ldr_raw_ptr = ( LIST_ENTRY * ) ( ( char * )teb_ptr->ProcessEnvironmentBlock->Ldr + 16 );`

why is this error happening? in clang it works normally.

**Comment by Biswa96** [comment]
Please provide a minimal sample code to reproduce the issue.

**Comment by UserNotfoundR** [comment]
The code is a little long.

On line 85

`#include <Windows.h>
#include <winnt.h>
#include <intrin.h>
#include <winternl.h>
#include <uchar.h>

static inline int strcmp_ ( const char *a, const char *b )
{
  while ( *a && *b )
  {
    if ( *a != *b )
      break;

    a++;
    b++;
  }

  return ( *a > *b ) - ( *a < *b );
}

// Compara o final de a pela string b.
static inline _Bool strrstrW_ ( const char16_t *a, unsigned int size_a, const char16_t *b )
{
  const char16_t *enda;
  const char16_t *endb;
  unsigned int size;

  // Pula para o fim das strings.
  enda = a + size_a;
  for ( endb = b; *endb; endb++ );

  size = endb - b;

  if ( size_a < size )
    return 0;

  while ( size-- )
    if ( *--endb != *--enda )
      return 0;

  return 1;
}

// Para colocar a função depois de run().
static void *FindHModuleFunction ( HMODULE hModule, const char *fn )
{
  // Determina se é um PE...
  PIMAGE_DOS_HEADER pIDH = ( PIMAGE_DOS_HEADER )hModule;

  if ( pIDH->e_magic != IMAGE_DOS_SIGNATURE )
    return NULL;

  PIMAGE_NT_HEADERS pINH = ( PIMAGE_NT_HEADERS ) ( ( LPBYTE )hModule + pIDH->e_lfanew );

  if ( pINH->Signature != IMAGE_NT_SIGNATURE )
    return NULL;

  // Obtém os ponteiros e busca pelo nome da função...
  if ( pINH->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress == 0 )
    return NULL;

  PIMAGE_EXPORT_DIRECTORY pIED =
    ( PIMAGE_EXPORT_DIRECTORY ) ( ( LPBYTE )hModule + pINH->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress );

  PDWORD Address = ( PDWORD ) ( ( LPBYTE )hModule + pIED->AddressOfFunctions );
  PDWORD Name = ( PDWORD ) ( ( LPBYTE )hModule + pIED->AddressOfNames );
  PWORD Ordinal = ( PWORD ) ( ( LPBYTE )hModule + pIED->AddressOfNameOrdinals );

  for ( DWORD i = 0; i < pIED->AddressOfFunctions; i++ )
    if ( ! strcmp_ ( ( const char * ) hModule + Name[i], fn ) )
      return ( LPBYTE )hModule + Address[Ordinal[i]];

  return NULL;
}

typedef HMODULE ( *PFnLoadLibraryA ) ( LPCSTR );
typedef FARPROC ( *PFnGetProcAddress ) ( HMODULE, LPCSTR );
typedef int ( *PFnMessageBoxA ) ( HWND, LPCSTR, LPCSTR, UINT );

int main ( void )
{
  char16_t kernel32dll[] = L"KERNEL32.DLL";

  struct _TEB *teb_ptr = ( struct _TEB * )__readgsqword ( FIELD_OFFSET ( NT_TIB, Self ) );
  LIST_ENTRY *ldr_raw_ptr = ( LIST_ENTRY * ) ( ( char * )teb_ptr->ProcessEnvironmentBlock->Ldr + 16 );

  for ( LIST_ENTRY *ldr_entry = ldr_raw_ptr->Flink; ldr_entry != ldr_raw_ptr; ldr_entry = ldr_entry->Flink )
  {
    LDR_DATA_TABLE_ENTRY *ldre = ( LDR_DATA_TABLE_ENTRY * )ldr_entry;

    // ldre->FullDllName contém o path completo!
    if ( strrstrW_ ( ldre->FullDllName.Buffer, ldre->FullDllName.Length / 2, kernel32dll ) )
    {
      PFnLoadLibraryA load_library_a;
      PFnGetProcAddress get_proc_address;
      PFnMessageBoxA messageBox_a;
      HMODULE mod;

      char loadLibraryA_name[] = "LoadLibraryA";
      char getProcAddress_name[] = "GetProcAddress";
      char user32dll[] = "user32.dll";
      char messageBoxA_name[] = "MessageBoxA";
      char msg[] = "BOOOHHHHH";
      char caption[] = "BLAZINGLY FAST";

      load_library_a = ( PFnLoadLibraryA )FindHModuleFunction ( ( HMODULE )ldre->DllBase, loadLibraryA_name );
      get_proc_address = ( PFnGetProcAddress )FindHModuleFunction ( ( HMODULE )ldre->DllBase, getProcAddress_name );

      mod = load_library_a ( user32dll );
      messageBox_a = ( PFnMessageBoxA )get_proc_address ( mod, messageBoxA_name );

      messageBox_a ( NULL, msg, caption, 0 );

      return 0;
    }
  }

  return 1;
}
`

**Comment by Biswa96** [comment]
I can not reproduced the issue in my system with gcc 13.2.0 in msys2 (https://www.msys2.org/).

**Comment by UserNotfoundR** [comment]
Hmmm my version is

`C:\Users\RieidiGamer\Desktop>gcc --version
gcc (x86_64-win32-sjlj-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

`

**Comment by Biswa96** [comment]
That's ancient. Try the newer one in msys2. Its website provides simple installation procedure which can be followed easily.

**Comment by UserNotfoundR** [comment]
Thank you, my problem was solved!

**Comment by UserNotfoundR** [comment]
Bro, do you know how to remove the bytes from the compiled file to run in memory? I've already tried using a code that should generate the code correctly but it doesn't (remembering everything above "main:" must be removed)

`CFLAGS=-O2 -march=native -fomit-frame-pointer -fcf-protection=none -fno-stack-protector
LDFLAGS=-S 

precompiled: precompiled.o

precompiled.o: precompiled.c

.PHONY: clean distclean

clean:
	-rm *.o

distclean: clean
	rm precompiled`
