### ISSUE TITLE
missing tcpxcv.h

### ISSUE THREAD

**Issue by marunguy** [mingw-w64/mingw-w64#46]
I am using the latest winlibs mingw-w6413.2.0 r7 in https://winlibs.com/.
When doing printing-related programming, a compiling error occurs because tcpxcv.h is missing.
Is it possible to add tcpxcv.h to mingw-w64?
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/tcpxcv/

**Comment by Biswa96** [comment]
I have sent a patch file to upstream mailing list which adds tcpxcv.h file https://sourceforge.net/p/mingw-w64/mailman/message/58763638/
