### ISSUE TITLE
Default to 64-bit time_t for i686 too PLEASE

### ISSUE THREAD

**Issue by defrag257** [mingw-w64/mingw-w64#47]
Default to 64-bit time_t for i686 too __PLEASE__.
This is currently controlled by __MINGW_USE_VC2005_COMPAT=1, but it is not by default enabled.
MSVC already default to 64-bit time_t since MSVC2005 with MSVCR80, and for DDKSDK, since Win2000 RTM with MSVCRT 6.10.
Linux world are going to resolve the Y2038 problem for 32-bit arches like armhf, and it's bad that mingw-w64 is still using 32-bit time_t for i686, and continuously generating Y2038-unsafe Windows x86 binaries which Microsoft already stopped generating nearly 20 years ago since MSVC2005.
MSVCRT 6.10 which contains Y2038-safe 64-bit time_t func defs like _time64 is available since Win2000 RTM, and no one need Win9x/NT3/4 nowadays. Those who use these ancient OSes should turn off the switch by themselves, not leave everybody a large number of Y2038-unsafe Windows x86 binaries even in 2024 and later.
Those who use libs assuming 32-bit time_t on 32-bit arches should also turn off the switch by themselves, rather than expect mingw-w64 stick to 32-bit time_t on i686 by default forever.

**Comment by lhmouse** [comment]
First this is not the correct place to file bug reports. Please send a mail to  <mingw-w64-public@lists.sourceforge.net> instead.

And second, have you been aware that every MSVC version prior to 2015 used to generate incompatible objects from versions to versions? They had no incompatibility to care about, because everything was literally incompatible. That's not the case for mingw-w64.

> The Microsoft C++ (MSVC) compiler toolsets in Visual Studio 2013 and earlier don't guarantee binary compatibility across major versions. You can't link object files, static libraries, dynamic libraries, and executables built by different versions of these toolsets. The ABIs, object formats, and runtime libraries are incompatible. [^1]

[^1]: https://learn.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170

**Comment by defrag257** [comment]
> First this is not the correct place to file bug reports. Please send a mail to [mingw-w64-public@lists.sourceforge.net](mailto:mingw-w64-public@lists.sourceforge.net) instead.
> 
> And second, have you been aware that every MSVC version prior to 2015 used to generate incompatible objects from versions to versions? They had no incompatibility to care about, because everything was literally incompatible. That's not the case for mingw-w64.
> 
> > The Microsoft C++ (MSVC) compiler toolsets in Visual Studio 2013 and earlier don't guarantee binary compatibility across major versions. You can't link object files, static libraries, dynamic libraries, and executables built by different versions of these toolsets. The ABIs, object formats, and runtime libraries are incompatible. [1](#user-content-fn-1-d56d76364cebed5450998993da87ea51)
> 
> ## Footnotes
> 1. https://learn.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170 [↩](#user-content-fnref-1-d56d76364cebed5450998993da87ea51)

That's not the reason why mingw-w64 stick to 32-bit time_t on i686. MSVCRT 6.10 is binary compatible with MSVCRT 6.00 which is redistributable MSVC6.0 runtime, and Microsoft deliver Windows components and DDK stuffs with 64-bit time_t linked to DDK MSVCRT 6.10, with binary compatibility with MSVC6.0 user programs.

**Comment by lhmouse** [comment]
> That's not the reason why mingw-w64 stick to 32-bit time_t on i686. MSVCRT 6.10 is binary compatible with MSVCRT 6.00 which is redistributable MSVC6.0 runtime, and Microsoft deliver Windows components and DDK stuffs with 64-bit time_t linked to DDK MSVCRT 6.10, with binary compatibility with MSVC6.0 user programs.

Do you expect that upgrading mingw-w64 requires _everything_ (not only DLLs, but static libraries) be rebuilt, especially those outdated and unmaintained?

**Comment by defrag257** [comment]
> > That's not the reason why mingw-w64 stick to 32-bit time_t on i686. MSVCRT 6.10 is binary compatible with MSVCRT 6.00 which is redistributable MSVC6.0 runtime, and Microsoft deliver Windows components and DDK stuffs with 64-bit time_t linked to DDK MSVCRT 6.10, with binary compatibility with MSVC6.0 user programs.
> 
> Do you expect that upgrading mingw-w64 requires _everything_ (not only DLLs, but static libraries) be rebuilt, especially those outdated and unmaintained?

It's not the problem. Those softwares still in maintainance could adjust code to build or adapt interfaces to those unmaintained by themselves. Or they just stick to an old release of mingw-w64 simply.

**Comment by lhmouse** [comment]
> For examples, a 64-bit time_t program can load 32-bit time_t plugins by explicitly declaring a seperate typedef  ...

You are suggesting a change in user code, so you should ask them whether they are willing to make it. As this is gonna be a _huge_ break, no change will be made unless we receive enough positive feedback.

**Comment by lhmouse** [comment]
> MSVC2005 already forced those who want to upgrade their compilers to make these changes nearly 20 years ago. Those who do not want to upgrade their codes stick to MSVC6.0, mingw32 or mingw-w64, but nowadays more and more are migrating to open-source toolchains like mingw-w64, and continuing to make increasing number of Y2038-unsafe executables day by day.

As stated above, they did not have backward incompatibility to worry about. But we do.

> Those new programs more likely support both MSVC20xx and mingw-w64 (and both i686 and x86_64, and even aarch64), and thus are aware of 64-bit time_t on 32-bit MSVC20xx. But a large number of the programs forget to define __MINGW_USE_VC2005_COMPAT=1 when compiled with mingw-w64 i686 and thus become Y2038-unsafe unintentionally.

So, is MSVC2015 _new_? If so, use UCRT which provides 64-bit `time_t` for you, period.

> I do not expect mingw-w64 to make the change immediately. I just explain that it's good to make, it's not hard to make and it's time to make.

No, the change is dangerously bad.

> Since 32-bit programs is getting less and less essential, the mingw-w64 i686 Y2038 problem may become no longer a problem in the far future.

Doesn't 'being less essential' imply that we shouldn't just break things (even unintentionally!) unless because of an emergency?

**Comment by defrag257** [comment]
> So, is MSVC2015 _new_? If so, use UCRT which provides 64-bit `time_t` for you, period.

> No, the change is dangerously bad.

So when will mingw-w64 recommend users to switch to UCRT in the near future?
So the upgrade to UCRT is even more dangerously bad as well, and you will not recommend it too even in the far-far future. Right?
What about give a configuration switch like `--mingw-use-vc2005-compat-time-t` when compiling mingw-w64 to switch it on by default?

> Doesn't 'being less essential' imply that we shouldn't just break things (even unintentionally!) unless because of an emergency?

It's a probability prediction. It may or may not become the reality in the future.
For a open-source contributer, it's okay. However, it make some softwares which promise like a ten-year support term a surprise.

**Comment by defrag257** [comment]
Thanks. I noticed that 12 will be UCRT by default.

By the way, if someone need 64-bit time_t i686 MSVCRT, a source change to mingw-w64-headers/crt/_mingw.h.in may be needed since some softwares may not use CC/CXX/CFLAGS/CXXFLAGS environment variables in compilation. This can be done by downstream or users.

**Comment by defrag257** [comment]
Thanks. I noticed that 12 will be UCRT by default.

By the way, if someone need 64-bit time_t i686 MSVCRT, a source change to mingw-w64-headers/crt/_mingw.h.in may be needed since some softwares may not use CC/CXX/CFLAGS/CXXFLAGS environment variables in compilation. This can be done by downstream or users.
