### ISSUE TITLE
bcyrpt.h: CNG Algorithm Pseudo-handles are missing

### ISSUE THREAD

**Issue by kou** [mingw-w64/mingw-w64#49]
The CNG Algorithm Pseudo-handles https://learn.microsoft.com/en-us/windows/win32/seccng/cng-algorithm-pseudo-handles documents say that `bcrypt.h` provides `BCRYPT_XXX_ALG_HANDLE` such as `BCRYPT_SHA256_ALG_HANDLE` but https://github.com/mingw-w64/mingw-w64/blob/master/mingw-w64-headers/include/bcrypt.h doesn't provide them.

Can we update our `bcrypt.h`?

**Comment by Biswa96** [comment]
> Can we update our `bcrypt.h`?

Yes, it is possible update that header ⏳

**Comment by kou** [comment]
Thanks!!!

**Comment by Biswa96** [comment]
The patch has been added in commit https://sourceforge.net/p/mingw-w64/mingw-w64/ci/55282977394ab3150412a15ae4ddfc0ebfb7e11d/

**Comment by kou** [comment]
Great!!!

**Comment by Biswa96** [comment]
This issue can be closed now.

**Comment by kou** [comment]
Thanks!
