### ISSUE TITLE
Feature request: implement ReadDirectoryChangesExW and FILE_NOTIFY_EXTENDED_INFORMATION

### ISSUE THREAD

**Issue by Wallby** [mingw-w64/mingw-w64#5]
winnt.h -> https://github.com/mingw-w64/mingw-w64/blob/master/mingw-w64-headers/include/winnt.h

**Comment by Biswa96** [comment]
@Wallby Those have been added in winnt.h. Please test it.

**Comment by Wallby** [comment]
@Biswa96 I am using chocolatey (didn't build from source).

**Comment by Biswa96** [comment]
It is possible to copy the winnt.h from this git repository and use it as is. Make sure to back up the current winnt.h in your system and test the new one with some dummy code.

**Comment by Wallby** [comment]
@Biswa96 do you mean winnt.h and winbase.h? (i.e. ReadDirectoryChangesExW is in winbase.h)

**Comment by Biswa96** [comment]
Both, if you wish. Just remember to backup the current ones.

**Comment by Biswa96** [comment]
* ReadDirectoryChangesExW was added in https://github.com/mingw-w64/mingw-w64/commit/9ca171081c6859fd0051cb72f0d2dd9f6dd81561
* FILE_NOTIFY_EXTENDED_INFORMATION was added in https://github.com/mingw-w64/mingw-w64/commit/35fa6bdbc14383c9078520492974ff5ab31ba796

**Comment by jon-y** [comment]
Closing as completed.
