### ISSUE TITLE
add IDebugClient5, IDebugControl4 and IDebugSymbols3

### ISSUE THREAD

**Issue by oltolm** [mingw-w64/mingw-w64#56]
I forked https://github.com/oltolm/verysleepy to make it work with mingw-w64. mingw-w64 does not support `IDebugClient5`, `IDebugControl4` and `IDebugSymbols3` so I had to use previous versions. Can someone add these interfaces?

**Comment by Biswa96** [comment]
Could you provide the steps to reproduce the issue? That project compiled fine in my system without any mingw-w64 changes. I used the ming-w64 branch of your fork.

**Comment by oltolm** [comment]
My fork does not use those interfaces and the upstream does not work with mingw-w64. You can see the changes here https://github.com/VerySleepy/verysleepy/commit/9ecfa3ea48b5db12b3f13fc8dc3ac16ea1257a2f#diff-57a6be94fcc66ff9ae181538bac60cc687e41328454019e64b5479ffa8c72cb9

**Comment by Biswa96** [comment]
Should I revert any commit in your fork? Or, should I use upstream repository to reproduce the issue?

**Comment by oltolm** [comment]
Upstream only support MSVC, it does not even support CMake. Reverting the commit does not work. You could manually revert the lines in `latesymbolinfo.h`
```
	// Dbgeng COM objects for minidump symbols
	Microsoft::WRL::ComPtr<IDebugClient5>  debugClient5;
	Microsoft::WRL::ComPtr<IDebugControl4> debugControl4;
	Microsoft::WRL::ComPtr<IDebugSymbols3> debugSymbols3;
};
```

**Comment by oltolm** [comment]
Thanks.

**Comment by Biswa96** [comment]
The patches were applied in the following commits.

* https://sourceforge.net/p/mingw-w64/mingw-w64/ci/aa3060039963b6e0c2950dd78b3db66faf8d79f8/
* https://sourceforge.net/p/mingw-w64/mingw-w64/ci/c37b1cd2058f25b02e8d7ffcf21db255e5cc3774/
* https://sourceforge.net/p/mingw-w64/mingw-w64/ci/039ff2e4cc01d275652aa6b8b08c17a574bd84aa/

**Comment by lazka** [comment]
also in MSYS2 repos now
