### ISSUE TITLE
_isw<>_l functions from ctype.h/wchar.h couldn't be used from MSVCRT

### ISSUE THREAD

**Issue by MehdiChinoune** [mingw-w64/mingw-w64#60]
because `_iswctype_l` is marked to be only available __MSVCR_VERSION>=0x800 (MSVCR80.dll). the other functions like `_iswalpha_l`, `iswupper_l`..etc couldn't be used from default MSVCRT.dll because the definitions rely on `_iswctype_l`.

How could an old function rely on a new one?

see: https://github.com/mingw-w64/mingw-w64/commit/e445c779

@lhmouse

Edit:

It looks like `_iswctype_l` is part of MSVCRT.dll!https://github.com/mingw-w64/mingw-w64/blob/d2491a9/mingw-w64-crt/lib-common/msvcrt.def.in#L1490

**Comment by lhmouse** [comment]
`_iswctype_l` does not exist in MSVCRT.DLL from Windows XP. If your program uses this function it won't run on XP.

**Comment by MehdiChinoune** [comment]
> `_iswctype_l` does not exist in MSVCRT.DLL from Windows XP. If your program uses this function it won't run on XP.
> 

But why other older functions are using it.
I have encountered an issue with postgresql, it doesn't use `_iswctype_l` directly but uses `_iswdigit_l` which is supposed to be available but fails to build because of its definition.

**Comment by lhmouse** [comment]
It's likely a bug. The macros should be updated.

**Comment by MehdiChinoune** [comment]
> `_iswctype_l` does not exist in MSVCRT.DLL from Windows XP. If your program uses this function it won't run on XP.

A simple Question: Is the default MSVCRT.dll not the same on each Windows version?
Which __MSCRT_VERSION__ correspond to each Windows?

I mean if those functions are available on default MSVCRT.dll on Windows>8.1 then that's an issue for me.

**Comment by lhmouse** [comment]
> A simple Question: Is the default MSVCRT.dll not the same on each Windows version? Which `__MSCRT_VERSION__` correspond to each Windows?

It's not.

On Windows XP, MSVCRT.DLL is supposed to cover symbols of Visual Studio 2003 (MSVCR70): https://github.com/mingw-w64/mingw-w64/blob/335ffe5b71d019c9ac5af29961fd872064ecb25c/mingw-w64-headers/configure.ac#L181-L183

Particularly, `printf()` on XP doesn't support `%lld`.

> I mean if those functions are available on default MSVCRT.dll on Windows>8.1 then that's an issue for me.

I have proposed a patch to undeclare those macros for MSVCRT: https://sourceforge.net/p/mingw-w64/mailman/message/58822937/

But I suspect that doesn't fix the issue for you. In UCRT `_iswctype_l` etc. ignore the locale parameter, so I suspect it's feasible to patch source code to replace `_iswctype_l` with `iswctype`, and `_iswalpha_l` with `iswalpha`, and so on.

**Comment by MehdiChinoune** [comment]
Sorry to be annoying, if those symbols are not in MSVCRT.DLL, Shouldn't they be removed from MSVCRT.def file?

**Comment by lhmouse** [comment]
> Sorry to be annoying, if those symbols are not in MSVCRT.DLL, Shouldn't they be removed from MSVCRT.def file?

They may be useful for linking newer DLLs, if that's desired anyway.
