### ISSUE TITLE
Lack function declaration of CM_Get_Device_Interface_PropertyW

### ISSUE THREAD

**Issue by CarterLi** [mingw-w64/mingw-w64#61]
https://learn.microsoft.com/en-us/windows/win32/api/cfgmgr32/nf-cfgmgr32-cm_get_device_interface_propertyw

Also it seems x86 version of `libcfgmgr32.a` lacks symbol of `CM_Get_Device_Interface_PropertyW` too ( but not x64 version ). Ref: https://github.com/fastfetch-cli/fastfetch/actions/runs/11256343208/job/31298002183#step:7:284

**Comment by Biswa96** [comment]
> Also it seems x86 version of `libcfgmgr32.a` lacks symbol of `CM_Get_Device_Interface_PropertyW` too

It is defined in 32 bit DEF.
https://github.com/mingw-w64/mingw-w64/blob/893f14bb28dd04262bffd5bfcd66d658b5014131/mingw-w64-crt/lib32/cfgmgr32.def#L130

**Comment by CarterLi** [comment]
Yeah, I forgot the stdcall shit.

**Comment by Biswa96** [comment]
I can try to add the missing function declaration in cfgmgr32.h tomorrow.
