### ISSUE TITLE
Please consider adding `winbrand.def` for platforms other than arm32

### ISSUE THREAD

**Issue by CarterLi** [mingw-w64/mingw-w64#63]
I use it to [query the OS name](https://github.com/fastfetch-cli/fastfetch/blob/dev/src/detection/os/os_windows.cpp#L34). It's strange to define it only for arm32 but not for others.

https://github.com/mingw-w64/mingw-w64/blob/893f14bb28dd04262bffd5bfcd66d658b5014131/mingw-w64-crt/libarm32/winbrand.def#L2

**Comment by lhmouse** [comment]
Please send a patch to mingw-w64-public@lists.sourceforge.net instead.

**Comment by Biswa96** [comment]
The winbrand import library does not exist in Windows SDK. Should it be added in mingw-w64?

**Comment by CarterLi** [comment]
It's useful. A lot of `Nt*` functions don't exist in Windows SDK but we have them, I believe we can do it for winbrand too.
