### ISSUE TITLE
Missing `interactioncontext.h`

### ISSUE THREAD

**Issue by 500-internal-server-error** [mingw-w64/mingw-w64#68]
I am trying to build [Aseprite](https://github.com/aseprite/aseprite), which used to support MinGW, but now only supports MSVC. [One of its dependencies](https://github.com/aseprite/laf/blob/main/os/win/winapi.h#L15C1-L15C32) expects `interactioncontext.h`, which unfortunately doesn't seem to exist. I found [Wine has it](https://gitlab.winehq.org/wine/wine/-/blob/master/include/interactioncontext.h?ref_type=heads), which I can copy manually as a workaround.

Could it be added to `mingw-w64-headers`?

**Comment by Biswa96** [comment]
patch sent https://sourceforge.net/p/mingw-w64/mailman/message/58837255/

**Comment by Biswa96** [comment]
The header file has been added in https://sourceforge.net/p/mingw-w64/mingw-w64/ci/058bc941cb6b3a93fd00783827841536bc45ce58/ commit. If that fixes the issue please close it.

**Comment by 500-internal-server-error** [comment]
How do I test it from MSYS2? Do I need to update and rebuild `mingw-w64-headers-git` locally?

**Comment by Biswa96** [comment]
The mingw-w64 headers package in msys2 in not updated yet. You can just copy paste the header file from this repository in `$MINGW_PRERIX/include` directory.

Make sure to remove it after testing. Otherwise, pacman will show error when new headers packages is provided by msys2.

**Comment by 500-internal-server-error** [comment]
Seems to work for my purposes, thanks.
