### ISSUE TITLE
ConsoleApi.h missing

### ISSUE THREAD

**Issue by lazka** [mingw-w64/mingw-w64#71]
The latest putty release fails to build because it's trying to use consoleapi.h which is not there: https://git.tartarus.org/?p=simon/putty.git;a=blob;f=windows/conpty.c;h=27e6f5523e5bde91cfd3f9e25a94b8ace738163b;hb=HEAD#l12

Which should provide things such as https://learn.microsoft.com/en-us/windows/console/createpseudoconsole

```
C:\msys64\clangarm64\bin\clang.exe -DHAVE_CMAKE_H -D_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE -D_CRT_SECURE_NO_WARNINGS -D_WINDOWS -D_WINSOCK_DEPRECATED_NO_WARNINGS -IC:/M/B/src/putty-0.82 -IC:/M/B/src/putty-build-CLANGARM64/CMakeFiles -IC:/M/B/src/putty-0.82/windows -IC:/M/B/src/putty-0.82/terminal -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wp,-D__USE_MINGW_ANSI_STDIO=1 -Xclang -fdiagnostics-format -Xclang clang -O3  -std=gnu99 -MD -MT windows/CMakeFiles/pterm.dir/conpty.c.obj -MF windows\CMakeFiles\pterm.dir\conpty.c.obj.d -o windows/CMakeFiles/pterm.dir/conpty.c.obj -c C:/M/B/src/putty-0.82/windows/conpty.c
C:/M/B/src/putty-0.82/windows/conpty.c:12:10: fatal error: 'consoleapi.h' file not found
````

I'll try to replace it with wincon.h in the meantime.

Note that putty only fails with mingw-w64 targeting win10 APIs since it only tries to build the conpty stuff in that case. In MSYS2 this means only clangarm64 is affected.

**Comment by Biswa96** [comment]
All consoleapi.h stuff in Windows SDK are glued in wincon.h in mingw-w64 headers. I am not sure if wincon.h in mingw-w64 should be split into those different headers. Waiting for lh or wbs.

**Comment by lhmouse** [comment]
The doc says that users should include windows.h.

https://github.com/MicrosoftDocs/Console-Docs/blob/2d4f2df928d45f6980b12feced5332fe1114a183/docs/createpseudoconsole.md?plain=1#L91

However it should be preferrable to follow Windows SDK 8.0, to move old functions into separate headers.

**Comment by Biswa96** [comment]
I have sent the patch upstream to add those header files https://sourceforge.net/p/mingw-w64/mailman/message/58848109/ . Please test it.

**Comment by jeremyd2019** [comment]
https://github.com/msys2/MINGW-packages/pull/22723 built successfully on arm64.
