### ISSUE TITLE
Support for some missing winsock functions ?

### ISSUE THREAD

**Issue by jcelerier** [mingw-w64/mingw-w64#8]
Hi,

I'm trying to build a software under mingw-w64 which uses: 

- GetAddrInfoExCancel
- GetAddrInfoExOverlappedResult

which do not seem to be available in the headers. If someone can give me a rough outline of the procedure I can try to add them in a PR.

**Comment by jcelerier** [comment]
addrinfoExA has the exact same problem

**Comment by jon-y** [comment]
Follow the declarations on MSDN, test them in your own applications to make sure they are correct.
Please submit the git format-patch file as an email attachment to the mailing list on sourceforge, this github repo is only setup as a mirror.

**Comment by jcelerier** [comment]
hi, I think this has already been fixed, I sent a mail earlier this month to the mailing list and someone come up with the patch
